### Change these variables:
@account = csa
@container = directions
@sasToken = sv=
###

### LIST Blobs for Storage Account Container
GET https://{{account}}.blob.core.windows.net/{{container}}?restype=container&comp=list&{{sasToken}}